# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2

general:
  artifacts:
    - coverage/redmine_issue_favicon_test/index.html

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.6-browsers-legacy
        environment:
          RAILS_ENV: test
          DB_HOST: 127.0.0.1
          TZ: /usr/share/zoneinfo/Asia/Tokyo
      - image: mysql:5.7
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --innodb-large-prefix=true --innodb-file-format=Barracuda
        environment:
          MYSQL_USER: root
          MYSQL_ALLOW_EMPTY_PASSWORD: yes

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: ready for redmine
          command: |
            REDMINE_BRANCH=master sh script/redmine-ready.sh
      - run: bundle install --path vendor/bundle --without postgresql rmagick && bundle update
      - run: bundle exec rake db:create RAILS_ENV=test
      - run: bundle exec rake db:migrate RAILS_ENV=test
      - run: bundle exec rake redmine:plugins:migrate RAILS_ENV=test
      - run:
          command: |
            bundle exec rake redmine_issue_favicon:test RAILS_ENV=test
      - run:
          command: |
            bundle exec rake redmine:plugins:migrate NAME=${CIRCLE_PROJECT_REPONAME} \
                    VERSION=0 RAILS_ENV=test
      - run:
          command: |
            mkdir -p /tmp/coverage
            cp -r coverage/redmine_issue_favicon_test /tmp/coverage/
      - store_artifacts:
          path: /tmp/coverage



